PLGMAG2V2-776: Add payment component to (BNPL) supported methods
MultiSafepay/magento2-hyva-checkout pull request #10
Opened 2024-07-24 12:56 UTC by vinodsowdagar

2024-08-28 16:06 UTC, danielcivit requested changes
- Check why are we removing the disclaimer block. 
- I know it's not within the initial scope of this task, but good opportunity to check for Payment Component support for other payment methods. (In "view/frontend/layout/hyva_checkout_components.xml"; are missing some card payment methods that supports the payment component, like visa, mastercard, maestro, amex. Maybe some other could also be included?

2024-08-28 16:58 UTC, vinodsowdagar commented on Payment/Method/MultiSafepayPaymentComponent.php
> -/**
Sorry something must have went wrong during a copy pasta at one point during development, I've added it back: https://github.com/MultiSafepay/magento2-hyva-checkout/commit/39d5b9b0cfc01a50ebc78aa65a04be23c1a2f6c0

2024-08-28 16:59 UTC, vinodsowdagar commented
> * Check why are we removing the disclaimer block.
> * I know it's not within the initial scope of this task, but good opportunity to check for Payment Component support for other payment methods. (In "view/frontend/layout/hyva_checkout_components.xml"; are missing some card payment methods that supports the payment component, like visa, mastercard, maestro, amex. Maybe some other could also be included?

That is a different task with a different ticket ID: PLGMAG2V2-789

2024-08-29 09:52 UTC, danielcivit approved these changes

2024-08-29 09:52 UTC, merged