MAGWIRE-22: Don't show Apple Pay on unsupported devices
MultiSafepay/magento2-hyva-checkout pull request #15
Opened 2024-09-27 10:31 UTC by vinodsowdagar

2024-10-01 12:02 UTC, danielcivit approved these changes

2024-10-01 13:02 UTC, danielcivit requested changes
Apple Pay only disappears after is selected.

2024-10-02 14:04 UTC, danielcivit approved these changes

2024-10-02 14:05 UTC, merged

2024-10-09 08:38 UTC, dhacquebord commented
@danielcivit @vinodsowdagar Thanks for the quick fix guys! Do you perhaps have an indication to when you will release a new version including this code?